//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_Id { get; set; }
        public string ClientID { get; set; }
        public string Client_Name { get; set; }
        public Nullable<long> Clinet_PIN { get; set; }
        public Nullable<int> DriversLicentNumber { get; set; }
        public Nullable<int> Car_Id { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<int> DestinatioID { get; set; }
        public Nullable<int> BookingStatus { get; set; }
    
        public virtual Booking_Status Booking_Status { get; set; }
        public virtual Car Car { get; set; }
        public virtual Destination Destination { get; set; }
    }
}
